<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TodoList.Core\TodoList.Core.csproj" />
    <ProjectReference Include="..\TodoList.Infrastructure\TodoList.Infrastructure.csproj" />
  </ItemGroup>

</Project>
